### ISSUE TITLE
Add the ability to set Tafsir similar to setting translation for Quran command

### ISSUE THREAD

**Issue by itzmk21** [galacticwarrior9/islambot#55]
Something like `/settafsir tafsir:`

**Comment by itzmk21** [comment]
Should the slash commands be `/tafsir get` and `/tafsir set`? or `/settafsir`?

**Comment by galacticwarrior9** [comment]
I prefer `/tafsir set` - even though this would be inconsistent with `/settranslation` - since subcommands will [eventually](https://github.com/discord/discord-api-docs/discussions/3581) be nested under their parent command on the UI; it would make sense for all tafsir-related commands to fall under `/tafsir`.

**Comment by itzmk21** [comment]
`/settranslation` could actually be renamed to `/translation set` and there could also be a new command that gets the current guild translation `/translation get` - possible idea
